#!/usr/bin/env python3
import shutil, os
from argparse import ArgumentParser, Namespace

BASE_DIR = os.path.dirname(__file__).strip(".")
SKEL = os.path.join(BASE_DIR, 'skel')

parser = ArgumentParser(
    "Static Manager",
    "static-init <path>"
)

def init(path: str):
    if not os.path.exists(path):
        print(f"Creating {path}...")
    print("Copying files...")
    shutil.copytree(SKEL, path, dirs_exist_ok=True)
    print("Done! ⚡")

parser.add_argument(
    "init",
    help = "Initialize a new project in the specified directory."
)

args: Namespace = parser.parse_args()

path = os.path.abspath(args.init)

if path != BASE_DIR:
    init(path)
else:
    print("Looks like you've set the base_dir of this Static, choose another location!")